services:
  db:
    image: postgres:15-alpine
    container_name: eventhub-db
    environment:
      POSTGRES_DB: eventhub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: eventhub-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eventhub_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db